"""Retrieval quality set: realistic patient questions and the document that answers each.

The questions are phrased the way people type, not copied from titles. A question counts as
a hit when its expected document is among the top three results.
"""

RETRIEVAL_QUESTIONS: list[tuple[str, str]] = [
    # practice
    ("what time do you open on saturday", "office-hours"),
    ("are you closed on sundays", "office-hours"),
    ("do you close over christmas and thanksgiving", "holiday-hours"),
    ("where is the clinic and how do I get there", "location-and-directions"),
    ("is there somewhere to leave my car", "parking"),
    ("I use a wheelchair, can I get into the building", "accessibility-and-mobility"),
    ("what is the best way to get in touch with the front desk", "contact-us"),
    ("which kinds of dentists work at your practice", "our-dentists"),
    ("do you use digital equipment and cameras", "dental-technology"),
    (
        "how do you make sure your tools are clean between patients",
        "sterilization-and-infection-control",
    ),
    # new patients
    ("what should I expect at my very first appointment", "first-visit-new-patient"),
    ("what do I need to have with me when I come in for the first time", "what-to-bring"),
    ("do I have to fill in paperwork before I arrive", "new-patient-forms"),
    ("what is included in a full first exam", "comprehensive-exam-and-xrays"),
    ("is the radiation from dental x-rays dangerous", "x-ray-safety"),
    ("how do I schedule a visit on your website", "booking-online"),
    (
        "can I speak to someone to make an appointment instead of using the website",
        "booking-by-phone-or-chat",
    ),
    # policies
    ("how much notice do you need if I cannot come", "cancellation-policy"),
    ("what happens if I turn up fifteen minutes late", "late-arrival-policy"),
    ("how can I move my visit to a different day", "rescheduling-an-appointment"),
    ("what if I forget to show up for my appointment", "missed-appointments"),
    ("will you remind me before my visit", "appointment-reminders"),
    ("how do you protect my personal health information", "privacy-of-your-information"),
    ("can I see my invoices and book online with an account", "patient-portal"),
    ("I want a copy of my x-rays to give to another dentist", "records-requests"),
    # insurance and payment
    ("which dental insurance companies do you work with", "insurance-plans-accepted"),
    ("who sends the claim to my insurer and when does it pay", "how-insurance-claims-work"),
    ("I do not have any dental coverage, can I still be seen", "paying-without-insurance"),
    ("can I pay with a credit card or in cash", "payment-methods"),
    ("is it possible to pay for expensive treatment in monthly installments", "payment-plans"),
    ("will I get a written quote before treatment starts", "treatment-estimates"),
    ("can I use my health savings account here", "fsa-and-hsa"),
    # pricing
    ("how are your prices decided", "pricing-overview"),
    ("how much is a standard check up with cleaning", "price-routine-exam-and-cleaning"),
    ("what does a scaling and root planing cost for each part of the mouth", "price-deep-cleaning"),
    ("what do I pay to have a cavity filled", "price-fillings"),
    ("how expensive is a porcelain cap for a tooth", "price-crowns"),
    ("what is the starting price for root canal treatment", "price-root-canal"),
    ("what does pulling a wisdom tooth cost", "price-extractions"),
    ("how much for a titanium tooth replacement", "price-dental-implants"),
    ("what does it cost to make my teeth whiter", "price-teeth-whitening"),
    ("how much are invisible braces", "price-orthodontics-and-aligners"),
    ("what do you charge if I come in with sudden pain", "price-emergency-visit"),
    # procedures
    ("what does the hygienist do during a regular cleaning", "what-happens-in-a-routine-cleaning"),
    ("what is scaling and root planing and why would I need it", "deep-cleaning-explained"),
    ("how is a cavity repaired with a white filling", "tooth-colored-fillings"),
    ("when does a damaged tooth need a cap and how is it fitted", "porcelain-crowns"),
    ("is a root canal painful and why is it needed", "root-canal-therapy"),
    ("why would a dentist remove a tooth", "tooth-extraction"),
    ("how does an artificial tooth root get attached to the jaw", "dental-implants"),
    ("how does professional bleaching work", "teeth-whitening"),
    ("how long do you wear clear trays to straighten teeth", "clear-aligners"),
    ("my gums bleed when I brush, what could be wrong", "gum-disease"),
    # aftercare
    ("what should I avoid after getting a filling", "aftercare-filling"),
    ("how do I look after the socket after having a tooth pulled", "aftercare-extraction"),
    ("my tooth is sore after root canal work, is that normal", "aftercare-root-canal"),
    ("my temporary crown fell off, what should I do", "aftercare-crown"),
    ("what can I eat after whitening treatment", "aftercare-teeth-whitening"),
    ("how do I care for myself after implant surgery", "aftercare-dental-implant"),
    # children, comfort
    ("when should my baby see a dentist for the first time", "children-first-dental-visit"),
    ("how much toothpaste should a toddler use", "childrens-tooth-care"),
    ("I get really scared at the dentist", "dental-anxiety"),
    ("do you offer laughing gas or other ways to stay calm", "sedation-options"),
    # emergency and oral health
    ("which dental problems count as urgent", "what-counts-as-a-dental-emergency"),
    ("my adult tooth was knocked out in a fall, what do I do", "knocked-out-tooth"),
    ("I have unbearable toothache tonight", "severe-toothache"),
    ("how often and how long should I brush", "brushing-and-flossing"),
    ("what can I do to stop getting cavities", "preventing-cavities"),
    ("why do my teeth hurt when I drink something cold", "sensitive-teeth"),
]

# Held out phrases for intent matching. None of them appears in data/intents.yaml.
INTENT_PHRASES: list[tuple[str, str]] = [
    ("hi, good to see you", "greeting"),
    ("hello, anybody around", "greeting"),
    ("hey, quick question please", "greeting"),
    ("what time are you open until on weekdays", "hours"),
    ("do you work saturdays", "hours"),
    ("is the practice open on bank holidays", "hours"),
    ("what is the clinic's street address", "location"),
    ("how can I get to your office by bus", "location"),
    ("where do I leave my car when I visit", "location"),
    ("what would a filling set me back", "pricing"),
    ("how much does a whitening session cost", "pricing"),
    ("what are the fees for an implant", "pricing"),
    ("is my dental plan accepted at your clinic", "insurance"),
    ("do you submit claims to my insurer", "insurance"),
    ("can I pay in instalments", "insurance"),
    ("I would like to make an appointment for a cleaning", "book"),
    ("do you have a free time on thursday", "book"),
    ("can you fit me in for a check-up next week", "book"),
    ("I need to change the time of my visit", "reschedule"),
    ("can my appointment be moved to the afternoon", "reschedule"),
    ("I would like to pick a new date for my booking", "reschedule"),
    ("please cancel the visit I have on monday", "cancel"),
    ("I am not able to attend, cancel it", "cancel"),
    ("is there a charge if I cancel at the last minute", "cancel"),
    ("does getting a crown hurt", "faq_procedure"),
    ("how long should I wait to eat after a filling", "faq_procedure"),
    ("what is involved in getting an implant", "faq_procedure"),
    ("my tooth is killing me and I need help right now", "emergency"),
    ("I knocked a tooth out playing football", "emergency"),
    ("my mouth is bleeding heavily", "emergency"),
    ("can I talk to a real person please", "human_handoff"),
    ("I want someone from the clinic to ring me", "human_handoff"),
    ("put me through to reception", "human_handoff"),
    ("thanks so much for the help", "thanks"),
    ("that is great, thank you", "thanks"),
    ("many thanks", "thanks"),
    ("what is the best pizza topping", "out_of_scope"),
    ("who is going to win the election", "out_of_scope"),
    ("write a short story about a dragon", "out_of_scope"),
]
